### ISSUE TITLE
macOS 14 installation fails

### ISSUE THREAD

**Issue by mf0o** [shellixyz/hd_fpv_video_tool#12]
Hey there.

Just a quick update on macOS 14.4 installation. 
For me it failed with errors E0425, E0609 because of ffmpeg-next 6. Version 7 worked for me

So I've modified the Cargo.toml: 
```
[[package]]
name = "ffmpeg-next"
version = "7.0.0"
```

and compiled it via `cargo install --path .`

Thanks pal.

**Comment by shellixyz** [comment]
Thanks for the heads up. I have updated the dependencies it should build fine on macOS 14.4 now according to your report.
