### ISSUE TITLE
thread main panick

### ISSUE THREAD

**Issue by hazcoper** [shellixyz/hd_fpv_video_tool#8]
hello

I am trying to add the osd and transcode a walksnail video and I keep getting this error. Other videos work fine, but this one does not

thread 'main' panicked at 'index out of bounds: the len is 512 but the index is 515', src/osd/overlay.rs:99:18

let me know if I should upload the video and osd files somewhere

thank you
Jose Mateus

**Comment by shellixyz** [comment]
Hello,

Please upload your OSD file and also your font. This error means that the OSD file is referring to a symbol 515 which should not exist. As far as I know fonts contain maximum 512 characters. Your OSD file might be corrupted.

**Comment by hazcoper** [comment]
[AvatarG0006.zip](https://github.com/shellixyz/hd_fpv_video_tool/files/11535001/AvatarG0006.zip)
Here is the osd file

**Comment by shellixyz** [comment]
I don't see a symbol 515 in this OSD file. Anyway I modified the code so that it would warn about invalid symbols in the OSD file instead of crashing.
